name: Deploy GeoVisor to Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Inyectar Mapillary Token
        run: |
          sed -i 's/__MAPILLARY_TOKEN__/${{ secrets.MAPILLARY_TOKEN }}/g' config/aplicacion.json

      - name: Configurar Páginas
        uses: actions/configure-pages@v4

      - name: Subir artefacto
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'

      - name: Desplegar a GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4